# Generated by Django 4.2.5 on 2023-09-22 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=255)),
                ('FileKey', models.CharField(max_length=255)),
                ('FileSize', models.BigIntegerField(default=0)),
                ('FileType', models.CharField(max_length=50)),
                ('FileCategory', models.CharField(default='', max_length=50)),
                ('UploadedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('LastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expiration_time', models.BigIntegerField()),
                ('LastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesharing.userfiles')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Shared_with', models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('Last_Modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('Expiry_Time', models.BigIntegerField(default=1000000)),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesharing.userfiles')),
                ('Requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesharing.userfiles')),
                ('PermTable', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='filesharing.permtable')),
                ('Requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
