# Generated by Django 4.2.5 on 2023-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='FileUrl',
            field=models.URLField(default=''),
        ),
    ]
