# Generated by Django 4.2.5 on 2023-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0004_permtable_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permtable',
            name='Owner_id',
            field=models.IntegerField(),
        ),
    ]
