# Generated by Django 4.2.5 on 2023-09-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0005_alter_permtable_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permtable',
            old_name='File_id',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='permtable',
            old_name='Requester_id',
            new_name='Requester',
        ),
    ]
