# Generated by Django 4.2.5 on 2023-09-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0007_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='PermTable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='filesharing.permtable'),
        ),
    ]
