# Generated by Django 4.2.5 on 2023-09-19 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0008_notifications_permtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='permtable',
            name='Last_Modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
