# Generated by Django 4.2.5 on 2023-09-19 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0009_permtable_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='permtable',
            name='Expiry_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
