# Generated by Django 4.2.5 on 2023-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0011_alter_permtable_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permtable',
            name='Expiry_Time',
            field=models.BigIntegerField(default=1000000),
        ),
    ]
